spring:
    application:
        name: ZooCrudApi
    profiles:
        active: prod
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/ZooCrudApi
        username: ZooCrudApi
        password: ZooCrudApi
    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate:
          ddl-auto: none
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
liquibase:
    contexts: prod
    change-log: classpath:config/liquibase/master.xml
server:
    port: 8080
